---
title: 'Chapter 6: Basic Graphs'
output: 
  github_document:
    toc: true
    toc_depth: 2
    fig_width: 5
    fig_height: 5
    dev: jpeg
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = F)
```

# Intro

# Bar plots

## Simple bar plots

Barplots are for displaying frequencies. Let's create a frequency table of `Arthritis$Improved`

The basic barplot. Lovely.

```{r count}
# Load library containing Arthritis dataset
library(vcd)
# Create freq table of values in Improved
counts <- table(Arthritis$Improved)
counts
```

```{r bar}
# Plot counts
barplot(counts,
        main="Simple Bar Plot",
        xlab="Improvement", ylab="Frequency")
```

Let's flip it.

```{r bar_horiz}
barplot(counts,
        # Flip it
        horiz=TRUE,
        main="Horizontal Bar Plot",
        xlab="Frequency", ylab="Improvement")
```

If we pass a matrix instead of a vector, we can produce stacked or grouped barplots.

```{r count_two_way}
# Create 2-way freq table for Improved and Treatment
counts <- table(Arthritis$Improved, Arthritis$Treatment)
counts
```

Stacked.

```{r bar_stacked}
# Plot Improvement by Treatment
barplot(counts,
        main="Stacked Bar Plot",
        xlab="Treatment", ylab="Frequency",
        col=c("red","yellow","green"),
        legend=rownames(counts))
```

Grouped.

```{r bar_grouped}
barplot(counts,
        main="Grouped Bar Plot",
        xlab="Treatment", ylab="Frequency",
        col=c("red","yellow","green"),
        legend=rownames(counts), beside=TRUE)
```

